### ISSUE TITLE
Cannot download ova-file, quota exceeded

### ISSUE THREAD

**Issue by tral** [TrainingByPackt/Command-Line-Fundamentals#1]
```
git lfs pull
```

```
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/TrainingByPackt/Command-Line-Fundamentals.git/info/lfs'
```

```
git checkout -f HEAD
```
```
Downloading Packt-CLI.ova (262 MB)
Error downloading object: Packt-CLI.ova (8024329): Smudge error: Error downloading Packt-CLI.ova (8024329b5ea1d5dcc1c531fb85b203794d85b4872b0136a0469c62174d59de88): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /Users/alekseitrubnikov/Projects/Command-Line-Fundamentals/.git/lfs/logs/20190715T095431.64469.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Packt-CLI.ova: smudge filter lfs failed
```

**Comment by dpst999** [comment]
i also need to download that file :(

**Comment by lowesusannah** [comment]
Same

**Comment by panzet** [comment]
Still the same problem:
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/TrainingByPackt/Command-Line-Fundamentals.git/info/lfs'

**Comment by rep-movsd** [comment]
I'm the author, I'll upload that file somewhere until Packt arranges more storage

**Comment by lowesusannah** [comment]
Thanks @rep-movsd!

**Comment by dpst999** [comment]
> I'm the author, I'll upload that file somewhere until Packt arranges more storage

When we will expect you to upload .....? 
Can you upload it on Google Drive .

**Comment by ghost** [comment]
> > I'm the author, I'll upload that file somewhere until Packt arranges more storage
> 
> When we will expect you to upload .....?
> Can you upload it on Google Drive .

Hi @rep-movsd 👋 we can't effectively progress with your book until this is resolved.  If it helps, I'll contact Packt and lean on them.

**Comment by ajhenley** [comment]
Same here

**Comment by rep-movsd** [comment]
Hi folks, I'm sorry for the delay - I had given a link to Packt long ago asking them to host the file somewhere but they haven't done anything and I have no reply from anyone on their side.

Here is my personal dropbox link to the file:
https://www.dropbox.com/s/ks9f7kcdsq7skhq/Packt-CLI.ova?dl=0
